### PR TITLE
Fix building with latest libfive version

### PR DESCRIPTION
**Pull request by julianschuler**
This PR fixes building this crate with the latest version of libfive. It also bumps the dependencies and Rust version.

Note: I bumped both `libfive` and `libfive-sys` to `0.2.0` but had to specify the `libfive-sys` dependency by path in the `Cargo.toml` file of `libfive`, since version `0.2.0` of `libfive-sys` is of course not (yet) present at crates.io.

I'm not sure how to resolve this dependency, maybe by merging this PR, uploading the new version of `libfive-sys` and then adding a new commit replacing the path dependency with the version before finally uploading the new version of `libfive`?

### CODE REVIEW

**Comment by virtualritz** [comment]
@julianschuler  Thanks heaps! :grin:

This is now be published with `v0.2.0` on `crates.io`.

There are some minimal API changes for the methods that write to disk.

**Comment by virtualritz** [comment]
@julianschuler

I just saw you completely removed `BRepSettings`. This was hidden in [this comit](https://github.com/virtualritz/libfive-rs/pull/5/commits/9c89a320fb906785a93de305c7a7ca7c4434165b) and nowhere mentioned. *Not cool.*

Can you elaborate?

**Comment by julianschuler** [comment]
This was a side effect of the latest libfive version not exposing this setting anymore.

**Comment by virtualritz** [comment]
I see. I guess we keep it that way then. 

Is there any rationale for this from Matt in the `libfive` release notes? I recall using different settings for some projects to achieve some better results.

**Comment by julianschuler** [comment]
I was unable to find anything in the changelog and a quick look at at the git log for the file was also without results.

**Comment by virtualritz** [comment]
Ok, sorry about the noise then. I'll write Matt and ask.

Thanks heaps again for the PR!

**Comment by virtualritz** [comment]
@julianschuler, I just published `v0.3` for both `libfive-sys` & `libfive` with your changes. Cheers!

Let me know if you want a mention as an author in `Cargo.toml` and what your full credentials/name/email would be there

**Comment by julianschuler** [comment]
Awesome! I don't need a mention though, thanks for the offer!

**Pull request merged**
